'use client';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { Scale, FileText, AlertTriangle, Ban, CheckCircle, ArrowLeft, Gavel } from 'lucide-react';

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5, delay, ease: [0.22, 1, 0.36, 1] as [number, number, number, number] },
});

const sections = [
  {
    icon: FileText,
    title: 'Acceptance of Terms',
    color: '#818CF8',
    content: `By creating an account or using NyaySaathi ("the Service"), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you must not use the Service.

These Terms apply to all users of NyaySaathi, including visitors, registered users, and any organization accessing the Service on behalf of its employees. NyaySaathi reserves the right to modify these Terms at any time. We will notify you of significant changes via email or an in-app notice. Continued use of the Service after changes constitutes acceptance of the new Terms.`,
  },
  {
    icon: CheckCircle,
    title: 'Permitted Use',
    color: '#34D399',
    bullets: [
      'Upload legal documents you own, have rights to, or have obtained lawful access to',
      'Use AI-generated risk reports for your personal or professional awareness and decision-making',
      'Share report summaries with your legal counsel, employer, landlord, or counterparty as part of negotiations',
      'Use the Service for commercial purposes (e.g., as a solo founder, freelancer, or business professional) within the limits of your account',
      'Integrate with our API (if you have been granted API access) in accordance with our API-specific addendum',
    ],
  },
  {
    icon: Ban,
    title: 'Prohibited Use',
    color: '#F87171',
    bullets: [
      'Uploading documents you do not have authorization to share or analyze',
      'Attempting to reverse-engineer, scrape, or extract the underlying AI models or prompts',
      'Using the Service to generate content intended to mislead parties in legal proceedings',
      'Reselling, sublicensing, or commercially redistributing AI-generated reports as a legal product or advisory service without our written consent',
      'Automating bulk document uploads in ways that intentionally degrade service quality for others',
      'Uploading documents containing personally identifiable information of third parties without their consent',
      'Using the Service for any illegal purpose under Indian law or applicable international law',
    ],
  },
  {
    icon: Scale,
    title: 'Intellectual Property',
    color: '#FB923C',
    content: `Your Documents: You retain full ownership of all documents you upload. NyaySaathi claims no intellectual property rights over your contract text.

AI-Generated Reports: The risk reports, clause summaries, risk scores, negotiation recommendations, and plain-language explanations generated by NyaySaathi are made available to you under a limited, non-exclusive, non-transferable license for your personal and professional use. You may not resell or commercially redistribute these reports as a standalone legal product.

NyaySaathi Platform: The NyaySaathi name, logo, product design, underlying software, AI architecture, prompt systems, and all associated intellectual property are owned exclusively by NyaySaathi and its licensors. You may not copy, modify, or create derivative works of the platform.`,
  },
  {
    icon: AlertTriangle,
    title: 'Limitation of Liability',
    color: '#FACC15',
    content: `To the fullest extent permitted by applicable law:

1. NyaySaathi's total aggregate liability to you for any claims arising from or related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim, or ₹1,000 (whichever is greater).

2. In no event shall NyaySaathi be liable for any indirect, incidental, special, consequential, or punitive damages — including but not limited to loss of profits, loss of data, loss of goodwill, or business interruption — even if advised of the possibility of such damages.

3. We are not liable for losses arising from: (a) your reliance on AI-generated analysis without consulting a qualified lawyer; (b) inaccuracies in AI analysis due to ambiguous or unusual legal language; (c) third-party service outages affecting Gemini AI or Firebase; (d) unauthorized access to your account due to password compromise.`,
  },
  {
    icon: Gavel,
    title: 'Governing Law & Dispute Resolution',
    color: '#A78BFA',
    content: `These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles.

Dispute Resolution: Any dispute arising from these Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration under the Arbitration and Conciliation Act, 1996 (India), with arbitration seated in Bengaluru, Karnataka.

Class Action Waiver: You agree to resolve disputes with us individually and not as part of any class action or representative proceeding.

Jurisdiction: For matters not subject to arbitration, you consent to the exclusive jurisdiction of the courts located in Bengaluru, Karnataka, India.`,
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', paddingTop: '5.5rem', paddingBottom: '5rem', position: 'relative', zIndex: 10 }}>
      <div className="container" style={{ maxWidth: 860 }}>

        {/* Back */}
        <motion.div {...fadeUp(0)} style={{ marginBottom: '2rem' }}>
          <Link href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', color: 'var(--text-muted)', textDecoration: 'none', fontWeight: 600 }}>
            <ArrowLeft size={14} /> Back to Home
          </Link>
        </motion.div>

        {/* Header */}
        <motion.div {...fadeUp(0.1)} style={{ marginBottom: '3rem' }}>
          <span className="section-chip chip-indigo" style={{ marginBottom: '1rem', display: 'inline-flex' }}>
            <Scale size={11} /> Terms of Use
          </span>
          <h1 style={{ fontFamily: "'Rozha One', serif", fontSize: 'clamp(2rem, 4vw, 3rem)', marginBottom: '0.75rem' }}>
            Terms of <span className="gradient-text">Use</span>
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: 1.7, maxWidth: 620 }}>
            These Terms govern your access to and use of NyaySaathi. Please read them carefully before using the Service.
          </p>
          <div style={{ display: 'flex', gap: '1.5rem', marginTop: '1.25rem', flexWrap: 'wrap' }}>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>📅 Effective: May 2026</span>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>🇮🇳 Governed by Indian Law</span>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>⚖️ Arbitration in Bengaluru</span>
          </div>
        </motion.div>

        {/* Key highlights */}
        <motion.div {...fadeUp(0.15)} className="glass-card" style={{ padding: '1.5rem', marginBottom: '2.5rem', borderColor: 'rgba(249,115,22,0.2)', background: 'rgba(249,115,22,0.04)' }}>
          <p style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--saffron)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '0.75rem' }}>⚡ Key Points</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
            {[
              { emoji: '📄', text: 'You own your documents — NyaySaathi claims no rights over them' },
              { emoji: '🤝', text: 'Reports are for your awareness — not a substitute for legal advice' },
              { emoji: '⚖️', text: 'Disputes resolved via arbitration in Bengaluru under Indian law' },
            ].map((item, i) => (
              <div key={i} style={{ display: 'flex', gap: '0.5rem', alignItems: 'flex-start' }}>
                <span style={{ fontSize: '1rem', flexShrink: 0 }}>{item.emoji}</span>
                <p style={{ fontSize: '0.83rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>{item.text}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {sections.map((section, si) => {
            const Icon = section.icon;
            return (
              <motion.div key={si} {...fadeUp(0.2 + si * 0.06)} className="glass-card" style={{ padding: '2rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem' }}>
                  <div style={{ width: 40, height: 40, borderRadius: 11, background: `${section.color}15`, border: `1px solid ${section.color}30`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <Icon size={18} color={section.color} />
                  </div>
                  <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-primary)' }}>{section.title}</h2>
                </div>

                {'content' in section && (
                  <div style={{ paddingLeft: '1rem', borderLeft: `2px solid ${section.color}30` }}>
                    <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.8, whiteSpace: 'pre-line' }}>{section.content}</p>
                  </div>
                )}

                {'bullets' in section && (
                  <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.6rem', paddingLeft: '0.5rem' }}>
                    {(section.bullets as string[]).map((bullet, bi) => (
                      <li key={bi} style={{ display: 'flex', gap: '0.6rem', alignItems: 'flex-start' }}>
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: section.color, marginTop: '0.5rem', flexShrink: 0 }} />
                        <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>{bullet}</p>
                      </li>
                    ))}
                  </ul>
                )}
              </motion.div>
            );
          })}
        </div>

        {/* Contact */}
        <motion.div {...fadeUp(0.5)} style={{ marginTop: '2.5rem', textAlign: 'center', padding: '1.5rem', borderRadius: 16, border: '1px solid var(--border-subtle)', background: 'rgba(255,255,255,0.02)' }}>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', lineHeight: 1.7 }}>
            Questions about these Terms? Contact us at{' '}
            <a href="mailto:legal@lexguardai.in" style={{ color: 'var(--saffron-light)', fontWeight: 700 }}>legal@lexguardai.in</a>
            {' '} · Also read our <Link href="/privacy" style={{ color: '#818CF8', fontWeight: 700 }}>Privacy Policy</Link>{' '}and{' '}
            <Link href="/disclaimer" style={{ color: '#818CF8', fontWeight: 700 }}>Disclaimer</Link>.
          </p>
        </motion.div>

      </div>
    </div>
  );
}
